william-dawson/NTPoly

Examples/GraphTheory/ReadMe.md
Examples/HydrogenAtom/ReadMe.md
Examples/PremadeMatrix/ReadMe.md
Examples/PremadeMatrix/main.cc

The newest version of Xcode (9.0) made some changes to the C++ standard library. As a result, the directions in the ReadMe files for the examples didn't have the correct instructions for linking.
The fix I found involves first compiling the code with a C++ compiler. Then, you link with -lc++ instead of -lstdc++.
In the long run run, it's probably better to explicitly compile the user's main program with a c++ compiler anyways since it is more consistent with the intel instructions.

Modified the readme files with the appropriate fixes for Clang 9

---

.travis.yml

New version of Trusty on Travis-CI comes with CMAKE version 3.9 preinstalled.

Removed CMAKE install line.

---

Source/Fortran/DistributedSparseMatrixModule.f90
Source/Fortran/TripletListModule.f90

In the triplet list module, there is now a function you can call which
redistributes a list of triplet lists to all processes on a given communicator.
This simplifies any type of global data redistribution. It is called now from
the DistributedSparseMatrix module's fill from triplet list routine.

A method for redistributing triplet lists.

---

Source/Fortran/ProcessGridModule.f90

* Communicators created in the constructor are freed.
* Allocated arrays are deallocated.
Source code not prettified.

Added a destructor for the process grid.

---

Source/Fortran/ChebyshevSolversModule.F90
Source/Fortran/DensityMatrixSolversModule.F90
Source/Fortran/ExponentialSolversModule.F90
Source/Fortran/GeometryOptimizationModule.F90
Source/Fortran/HermiteSolversModule.F90
Source/Fortran/InverseSolversModule.F90
Source/Fortran/LinearSolversModule.F90
Source/Fortran/PolynomialSolversModule.F90
Source/Fortran/RootSolversModule.F90
Source/Fortran/SignSolversModule.F90
Source/Fortran/SquareRootSolversModule.F90
Source/Fortran/TrigonometrySolversModule.F90

Every time we copy the solver parameters, we should properly
clean them up.
I also did a little more code cleanup.

Solver parameter destructor is properly called

---

CMakeLists.txt
UnitTests/CurrentTest.sh

So of course the releases were passing their regression tests
when checked out from git, but the actual standalone releases
were having problems. It would try to ask git for a unit test, but
since it isn't a git repository it was failing.

Fix to the release version unit tests.

---

Source/Fortran/GeometryOptimizationModule.F90

* The new code seems to work
* User should be careful about spin degeneracy
* Note that there is no need to work on add and subtract branches
* Reference:
* The Journal of Chemical Physics 123, 044107 (2005)
* The Journal of Chemical Physics 132, 124104 (2010)

Reimplement purification-based density matrix extrapolation

---

Source/Fortran/PermutationModule.F90
Source/Fortran/ProcessGridModule.F90
Source/Fortran/TripletListModule.F90
Source/Fortran/distributed_algebra_includes/MatrixMultiply.f90
Source/Fortran/solver_includes/AppendToVector.f90
Source/Fortran/sparse_includes/PruneList.f90

@william-dawson  This is to dismiss some warnings from NAG Fortran. I'm not sure if you are ok with adding `CALL DestructPermutation(this)` to `PermutationModule.F90`. Please let me know : )

Add a few deallocate statements

---

Source/Fortran/MatrixMarketModule.F90
Source/Fortran/distributed_includes/WriteToMatrixMarket.f90

This includes two fixes.
* On some versions of intel, the header wasn't being written properly using the write_at command. Switching to a file view setup (as is used for the entries of the matrix) things appear to work.
* Cleaned up the matrix output.

Fixes for writing to matrix market

---

Source/Fortran/MatrixMarketModule.F90

Nothing but changing all WRITE(xxx, '(A A)') ... to WRITE(xxx, '(2A)') ...
Otherwise I got the following error message with ifort (version 19):
```
[14/39] Building Fortran object Source/Fortran/CMakeFiles/NTPoly.dir/SolverParametersModule.F90.o
FAILED: Source/Fortran/CMakeFiles/NTPoly.dir/MatrixMarketModule.F90.o include/matrixmarketmodule.mod 
/opt/intel/impi/2018.2.199/bin64/mpiifort  -I../Source/Fortran -O3 -fpp -module include -c Source/Fortran/CMakeFiles/NTPoly.dir/MatrixMarketModule.F90-pp.f90 -o Source/Fortran/CMakeFiles/NTPoly.dir/MatrixMarketModule.F90.o
Source/Fortran/CMakeFiles/NTPoly.dir/../Source/Fortran/MatrixMarketModule.F90(139): error #7421: A constant or general expression must appear in a format list in this context.   [AAA]
WRITE(outstring, '(A A A)') …
```

Fix compilation with ifort

---

.github/workflows/ci.yml
Source/Fortran/MatrixConversionModule.F90
Source/Fortran/MatrixReduceModule.F90
Source/Fortran/PSMatrixModule.F90
Source/Fortran/TripletListModule.F90
Source/Fortran/comm_includes/ReduceAndComposeMatrix.f90
Source/Fortran/comm_includes/ReduceAndSumMatrix.f90
Source/Fortran/distributed_includes/FillMatrixFromTripletList.f90
Source/Fortran/distributed_includes/FillMatrixIdentity.f90
Source/Fortran/distributed_includes/FillMatrixPermutation.f90
Source/Fortran/distributed_includes/GatherMatrixToAll.f90
Source/Fortran/distributed_includes/RedistributeData.f90
UnitTests/test_psmatrix.py

This update includes a "prepartitioned" option for fill matrix from triplet list, so that if you have already prepartitioned the data you can skip the communication step.
I also modified the SNAP routine to remove any communication there.

Optimizations related to matrix conversion

---

Source/Swig/CMakeLists.txt
Source/Swig/ConfigPython.cmake

Previously, in order to get the python bindings to work on the mac, I had built a special configure script to search for the python libraries. Unfortunately, this was breaking things when I tried to use conda. I learned today that I could side step this issue using the linker flags `-flat_namespace -undefined suppress`. This will defer the search for python libraries until run time, at which point it works automatically.

Simplified configuration on a Mac

---

.github/workflows/ci.yml
Targets/Linux.cmake
UnitTests/before_install.sh
UnitTests/run_cmake.sh

Improvements/Bug Fixes for CI.
Major fix:
1. -fopenmp had to replace -openmp -lgomp otherwise the code cryptically fails to compile. #166
2. Mac require reinstall gcc for some reason
ETC
1. Switched Make to Ninja.
2. Upload artifacts so that you can debug easier.
3. Removed some unneeded packages/
4. Added doxygen/Ford. In the future we should auto-deploy documentation.
5. Mac goes to python3
6. Removed some lines that are artifacts of Travis-CI

CI Improvements

---

Source/Fortran/DensityMatrixSolversModule.F90

Fix for #163 
Basically, if we set all of the thresholding to zero, we can arrive at a situation where the change in the matrix at a given step is a matrix full of zeros. In the PM method, we divide by the trace of this update matrix, which will be exactly zero, which is of course a disaster. This modification will make sure this case never happens. Nonetheless, there is probably some remaining numerical instability in the PM method near convergence because you are dividing a small number by another small number.

Early exist condition for PM solver

---

.github/workflows/ci.yml
Source/Fortran/ProcessGridModule.F90
Source/Fortran/distributed_algebra_includes/MatrixMultiply.f90
UnitTests/run_ci_test.sh

~~Draft until performance tests confirm no degradation.~~
Fix for #143, where the code hangs if the maximum number of threads is set to 1. It seems that OpenMPI has this issue too now.
What seems to happen is that the task scheduling thread never sleeps, so no calculations are actually done, and a deadlock is reached. I think other implementations of MPI (Fujitsu, Intel, older OpenMPI) would have the main thread sleep during the polling operations, so this wasn't an issue. This is the most brute force of fixes: if the threads are capped, we force task wait. But this may imply that if you're using openmpi there will be performance left on the table, so it could be worth another look in the future.

Draft: Fix max thread capping issue

---

Source/Fortran/CholeskySolversModule.F90
Source/Fortran/DataTypesModule.F90
Source/Fortran/TimerModule.F90

There were three small bugs related to Fortran MPI datatypes and the MPI module scheme, which popped up during the compilation of FHI-aims in serial mode.

Small fixes for Fortran MPI datatypes and Module

---

Source/Fortran/DataTypesModule.F90
Source/Fortran/PSMatrixModule.F90
Source/Fortran/distributed_includes/WriteMatrixToBinary.f90

When reading a text matrix market matrix, NTPoly was storing the total number of matrix elements into a standard integer. For reading/writing binary, the same issue existed. This fixes those issues.
This modifies the format of the binary matrix in a non-backwards compatible way. This is one more reason to move to version 3.

Fix I/O for large number of entries (> integer)

---

Source/Fortran/ProcessGridModule.F90

It's useful for the calling code to be able to compute

Make the compute grid size function public

---

UnitTests/test_solvers.py

Make sure we can fully converge any test

Turn off automatic convergence in unit tests

---

Source/Fortran/EigenSolversModule.F90
Source/Fortran/dense_includes/ConstructMatrixDFromS.f90
Source/Fortran/distributed_algebra_includes/MatrixMultiply.f90
Source/Fortran/distributed_includes/FillMatrixFromTripletList.f90
Source/Fortran/distributed_includes/TransposeMatrix.f90
Source/Fortran/eigenexa_includes/EigenSerial.f90
Source/Fortran/eigenexa_includes/EigenToNT.f90
Source/Fortran/sparse_includes/DenseBranch.f90

In this merge request, I've tried to be more aggressive about deallocating datastructures as soon as they're not needed inside the memory intensive operations (multiplication, dense eigenvalue problem).

Memory Optimizations

---

Examples/ComplexMatrix/main.cc
Examples/GraphTheory/main.cc
Examples/HydrogenAtom/main.cc
Examples/MatrixMaps/main.cc
Examples/PremadeMatrix/main.cc
Source/C/ProcessGrid_c.h
Source/CPlusPlus/ProcessGrid.cc
Source/CPlusPlus/ProcessGrid.h
Source/Fortran/ProcessGridModule.F90
Source/Wrapper/ProcessGridModule_wrp.F90
UnitTests/test_chemistry.py
UnitTests/test_matrix.py
UnitTests/test_psmatrix.py
UnitTests/test_psmatrixalgebra.py
UnitTests/test_solvers.py

Remove `be_verbose` option from the process grid
