- ReadMe.md
Modifications to link to all the websites.
> Proofreading

- Source/Fortran/DensityMatrixSolversModule.f90
- Source/Fortran/LoggingModule.f90
- Source/Fortran/MinimizerSolversModule.f90
- UnitTests/CurrentTest.sh
Now it actually computes the energy. I don't think the overhead
is so bad, because it just requires a local pairwise multiply.
It also prints the energy out now, which is very helpful to the
user. I further modified the logging module to print more digits.
> Modified the convergence criteria for the chemistry solvers.

- Examples/GraphTheory/main.cc
- Examples/HydrogenAtom/main.cc
- Examples/PremadeMatrix/main.cc
For some reason, there was a lot of code that had been left commented out.
> Fixed an error in the premade matrix example.

- .travis.yml
- UnitTests/travis_before_install.sh
There seemed to be some error with my cached openmpi.
> Fix travis ci bug

- Source/Fortran/DensityMatrixSolversModule.f90
- Source/Wrapper/DensityMatrixSolversModule_wrp.f90
Also with some minor changes:
* Unified the usage of double precision numbers which slightly
improves the convergence of HPCP.
* Moved the iteration output to the end of each loop.
* Added band structure energy as an optional argument to each
of the density matrix solver API.
Source code not prettified.
> DM: Added canonical purification by Palser and Manolopoulos.

- CMakeLists.txt
- Examples/CMakeLinkage/CMakeLists.txt
- Examples/CMakeLinkage/ReadMe.md
- Source/C/CMakeLists.txt
- Source/CPlusPlus/CMakeLists.txt
- Source/Fortran/CMakeLists.txt
- Source/Wrapper/CMakeLists.txt
This also includes an example of how to link your Cmake library against
NTPoly.
> Exporting of the target for CMake.

- Source/CPlusPlus/ProcessGrid.h
- Source/CPlusPlus/TripletList.h
> Fixes to C++ documentation

- Examples/ComplexMatrix/ReadMe.md
- Examples/GraphTheory/ReadMe.md
- Examples/HydrogenAtom/ReadMe.md
- Examples/OverlapMatrix/ReadMe.md
- Examples/PremadeMatrix/ReadMe.md
Fixes to the examples instructions
> Instructions

- Source/Fortran/DataTypesModule.F90
- Source/Fortran/DensityMatrixSolversModule.F90
- Source/Fortran/LinearSolversModule.F90
- Source/Fortran/MatrixMapsModule.F90
- Source/Fortran/MatrixMemoryPoolModule.F90
- Source/Fortran/MatrixReduceModule.F90
- Source/Fortran/PSMatrixAlgebraModule.F90
- Source/Fortran/PSMatrixModule.F90
- Source/Fortran/PermutationModule.F90
- Source/Fortran/ProcessGridModule.F90
- Source/Fortran/SMatrixAlgebraModule.F90
- Source/Fortran/SMatrixModule.F90
- Source/Fortran/TrigonometrySolversModule.F90
- Source/Fortran/TripletListModule.F90
- Source/Fortran/TripletModule.F90
- Source/Fortran/distributed_includes/WriteMatrixToBinary.f90
- Source/Fortran/distributed_includes/WriteToMatrixMarket.f90
This pull request includes @vyu16 's modifications for NAG compilation. He also mentioned that `sizeof` cannot be used with NAG, so I have replaced those calls with MPI calls.
(It looks like I messed up the procedure for updating a pull request, so here's a new one...)
> Vyu16 nag compilation

- Source/Fortran/comm_includes/ReduceAndSumMatrixCleanup.f90
Fix the matrix summation for the case of empty matrices
> Fix to matrix reduce module.

- Source/CPlusPlus/ProcessGrid.cc
- Source/CPlusPlus/ProcessGrid.h
Which uses INT to store MPI_COMMs
> Fix for intel.

- Source/Fortran/MatrixMarketModule.F90
> Proposed fix for intel and cray

- .travis.yml
- UnitTests/travis_before_install.sh
- UnitTests/travis_run_cmake.sh
#117 
I've added a travis-ci instance that compiles the code with all debug flags on, and runs a test. It is not possible to run all of the regression tests, but even one should be good enough to detect any serious issues.
> Check All Travis-CI Run

- Citations.bib
- Source/C/DensityMatrixSolvers_c.h
- Source/CPlusPlus/DensityMatrixSolvers.cc
- Source/CPlusPlus/DensityMatrixSolvers.h
- Source/Fortran/DensityMatrixSolversModule.F90
- Source/Wrapper/DensityMatrixSolversModule_wrp.F90
- UnitTests/test_chemistry.py
There is also a small code reduction change in test_chemistry.
Currently, NTPoly offers no solution for estimating the homo and
lumo, but if it is available this routine can be faster.
> Implemented Rubensson's scale and fold method.

- Source/CPlusPlus/CMakeLists.txt
- Source/Fortran/CMakeLists.txt
- Source/Wrapper/CMakeLists.txt
- Targets/Intel.cmake
- Targets/Linux.cmake
- UnitTests/travis_run_cmake.sh
This way you can build on linux without using the target file.
> Automatic PIC flag

- UnitTests/test_chemistry.py
Clearly the code was robust to this issue, but it should be
at the right place...
> Fixed the location of the gap in the unit tests.

- .travis.yml
- CONTRIBUTING.md
- Examples/ComplexMatrix/compare.py
- Examples/ComplexMatrix/generate.py
- Examples/ComplexMatrix/main.f90
- Examples/ComplexMatrix/main.py
- Examples/GraphTheory/ReadMe.md
- Examples/GraphTheory/main.py
- Examples/GraphTheory/visualize.py
- Examples/HydrogenAtom/ReadMe.md
- Examples/HydrogenAtom/main.py
- Examples/HydrogenAtom/visualize.py
- Examples/MatrixMaps/main.py
- Examples/OverlapMatrix/visualize.py
- Examples/PremadeMatrix/main.py
- UnitTests/helpers.py
- UnitTests/test_build.py
- UnitTests/test_chemistry.py
- UnitTests/test_matrix.py
- UnitTests/test_psmatrix.py
- UnitTests/test_psmatrixalgebra.py
- UnitTests/test_solvers.py
- UnitTests/travis_before_install.sh
- UnitTests/travis_lint.sh
This includes adding a linting stage to Travis-CI
> Code cleanup via flake8

- .travis.yml
- Examples/ComplexMatrix/ReadMe.md
- Examples/GraphTheory/ReadMe.md
- Examples/HydrogenAtom/ReadMe.md
- Examples/MatrixMaps/ReadMe.md
- Examples/PremadeMatrix/ReadMe.md
- Source/CPlusPlus/CMakeLists.txt
- UnitTests/travis_before_install.sh
- UnitTests/travis_run_cmake.sh
Ubuntu 18.04 bionic is now available on Travis-CI. This allows us to simplify the CI system significantly, since important dependencies like Swig and MPI are now up to date in apt's repository's. 
While make these changes, a linking bug emerged that happens if you try to build on Linux without a toolchain file. This update also fixes this issue.
> Build System Improvements

- .github/workflows/ci.yml
- ReadMe.md
- UnitTests/travis_before_install.sh
Testing out the github actions approach.
> Github Actions CI Test

- Source/Fortran/DMatrixModule.F90
- Source/Fortran/SMatrixAlgebraModule.F90
- Source/Fortran/dense_includes/ComposeMatrix.f90
- Source/Fortran/dense_includes/ConstructMatrixSFromD.f90
- Source/Fortran/sparse_includes/DenseBranch.f90
- UnitTests/test_matrix.py
This fixes some memory leaks that can occur with the Fujitsu compilers due to incomplete Fortran 2003 support. It also includes a few simplifications of the code which is always good.
> Memory leak fix in the dense block branch.

- .github/workflows/ci.yml
Github Actions was not being triggered by pull requests.
> Fix deployment model.

- Source/Fortran/PSMatrixModule.F90
- Source/Fortran/distributed_includes/GatherMatrixToAll.f90
- Source/Fortran/distributed_includes/GatherMatrixToProcess.f90
- Source/Fortran/distributed_includes/PrintMatrix.f90
Added the feature to gather the matrix on to all processes.
> Gather on all

- Examples/HydrogenAtom/main.f90
- Examples/OverlapMatrix/main.f90
- Examples/PremadeMatrix/main.f90
> Permutation destructor added to examples.

- .github/workflows/ci.yml
- Examples/HydrogenAtom/ReadMe.md
- Examples/OverlapMatrix/ReadMe.md
- Source/Fortran/PSMatrixModule.F90
- Source/Fortran/ProcessGridModule.F90
- Source/Fortran/TrigonometrySolversModule.F90
- Source/Fortran/sparse_includes/IncrementMatrix.f90
- Source/Fortran/sparse_includes/PairwiseMultiplyMatrix.f90
- Source/Fortran/triplet_includes/SortTripletList.f90
- Source/Wrapper/PSMatrixModule_wrp.F90
- Source/Wrapper/TripletListModule_wrp.F90
- UnitTests/before_install.sh
- UnitTests/lint.sh
I've added a small awk script to the linter to find violations of the 80 column limit rule.
> 80 Column Limit Enforcement

- Source/Fortran/TripletListModule.F90
> Fix compilation with gcc-10

- .github/workflows/ci.yml
- Targets/Mac-conda.cmake
- UnitTests/before_install.sh
- UnitTests/check_examples.sh
- UnitTests/lint.sh
- UnitTests/run_ci_test.sh
- UnitTests/run_cmake.sh
- environment.yml
I added an environments.yml file so that NTPoly can easily be used on a conda environment. I modified the CI to use this one (for Linux) to ensure the environment works. I also modified the build in the CI to use ninja which seems faster even in the cloud.
> Use Anaconda in the CI Stage

- CITATION.cff
I added a github style citation file.
> Github Style Citation File

- .github/workflows/ci.yml
- Source/Fortran/CholeskySolversModule.F90
- Source/Fortran/DMatrixModule.F90
- Source/Fortran/MatrixMemoryPoolModule.F90
- Source/Fortran/MatrixReduceModule.F90
- Source/Fortran/PSMatrixAlgebraModule.F90
- Source/Fortran/PSMatrixModule.F90
- Source/Fortran/SMatrixAlgebraModule.F90
- Source/Fortran/SMatrixModule.F90
- Source/Fortran/SVectorModule.F90
- Source/Fortran/TripletListModule.F90
- Source/Fortran/TripletModule.F90
- UnitTests/generate_elsi.py
This set of commits includes a script that can generate a version of the NTPoly source code which uses no file includes for the purpose of exporting to ELSI. In addition to the script, I've set github actions to build and export the generated files, which can be downloaded and integrated into ELSI easier.
> ELSI Exporter

- Source/Fortran/DensityMatrixSolversModule.F90
- Source/Fortran/PSMatrixAlgebraModule.F90
- UnitTests/test_build.py
A routine that multiplies a matrix on the left and on the right. This can reduce the lines of code in a few places.
> Code reduction: similarity transform routine

- Source/C/Analysis_c.h
- Source/CPlusPlus/Analysis.cc
- Source/CPlusPlus/Analysis.h
- Source/Fortran/AnalysisModule.F90
- Source/Fortran/PSMatrixAlgebraModule.F90
- Source/Wrapper/AnalysisModule_wrp.F90
- UnitTests/test_build.py
- UnitTests/test_solvers.py
This new feature allows you to take an NxN matrix, and convert it to a KxK matrix (K < N) whose eigenvalues are identical to the first K eigenvalues of the original matrix.
> Reduce dimension feature

- Examples/HydrogenAtom/main.cc
- Examples/HydrogenAtom/main.f90
- Examples/HydrogenAtom/main.py
- Examples/PremadeMatrix/main.cc
- Examples/PremadeMatrix/main.f90
- Examples/PremadeMatrix/main.py
- Source/C/DensityMatrixSolvers_c.h
- Source/C/GeometryOptimization_c.h
- Source/CPlusPlus/DensityMatrixSolvers.cc
- Source/CPlusPlus/DensityMatrixSolvers.h
- Source/CPlusPlus/GeometryOptimization.cc
- Source/CPlusPlus/GeometryOptimization.h
- Source/Fortran/AnalysisModule.F90
- Source/Fortran/DensityMatrixSolversModule.F90
- Source/Fortran/GeometryOptimizationModule.F90
- Source/Wrapper/DensityMatrixSolversModule_wrp.F90
- Source/Wrapper/GeometryOptimizationModule_wrp.F90
- UnitTests/test_chemistry.py
This will break many things...
> Fraction number of electrons

- Source/Fortran/MatrixMapsModule.F90
Before it was just floating point, but this will allow you to send integers as well.
> Maps with integer optional data

- Source/Fortran/CholeskySolversModule.F90
- Source/Fortran/DMatrixModule.F90
- Source/Fortran/EigenBoundsModule.F90
- Source/Fortran/MatrixMemoryPoolModule.F90
- Source/Fortran/PMatrixMemoryPoolModule.F90
- Source/Fortran/PSMatrixAlgebraModule.F90
- Source/Fortran/PSMatrixModule.F90
- Source/Fortran/SMatrixModule.F90
- Source/Fortran/TripletListModule.F90
- Source/Fortran/dense_includes/ConstructEmptyMatrix.f90
- Source/Fortran/dense_includes/ConstructMatrixMemoryPool.f90
- Source/Fortran/solver_includes/UnpackCholesky.f90
- Source/Fortran/sparse_includes/ConstructEmptyMatrix.f90
- Source/Fortran/sparse_includes/ConstructMatrixFromTripletList.f90
- Source/Fortran/triplet_includes/ConstructTripletList.f90
- Source/Wrapper/MatrixMemoryPoolModule_wrp.F90
- Source/Wrapper/PMatrixMemoryPoolModule_wrp.F90
- Source/Wrapper/SMatrixModule_wrp.F90
- Source/Wrapper/TripletListModule_wrp.F90
> Unify code path of subroutine/function version of constructors

- Source/C/DensityMatrixSolvers_c.h
- Source/CPlusPlus/DensityMatrixSolvers.cc
- Source/CPlusPlus/DensityMatrixSolvers.h
- Source/Fortran/DensityMatrixSolversModule.F90
- Source/Wrapper/DensityMatrixSolversModule_wrp.F90
- UnitTests/test_chemistry.py
Useful for things like dual basis methods, mixing, etc.
> Mcweeny step helper routine

- Source/Swig/ConfigPython.cmake
- UnitTests/before_install.sh
It appears to be the case that `distutils` is depreciated. Therefore, I modified the python path searching script to use `sysconfig` as recommend by ChatGPT.
> Fix CI on Mac
